FROM python:3.7
WORKDIR /app

COPY py_backend /app/py_backend
COPY app.py /app
COPY requirements.txt /app

RUN pip install -r ./requirements.txt

EXPOSE 5000

# CMD ["gunicorn", "--preload", "--bind=:5000", "--forwarded-allow-ips=localhost", "app:app"]

ENTRYPOINT [ "flask" ]
CMD ["run", "--host=0.0.0.0", "--port=5000"]